import type { Metadata } from "next";

import "./globals.css";
import Layout from "@/layout/Layout";

import { yekan } from "@/utils/fonts";
import NextAuthProvider from "src/providers/NextAuthProvider";

export const metadata: Metadata = {
  title: " کلنیک تخصصی ماشین",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
        <NextAuthProvider>
          <Layout>{children}</Layout>
        </NextAuthProvider>
      </body>
    </html>
  );
}
